version: '2'

services:
  server:
    container_name: nSERVER
    build: .
    image: cameric/8weike-server:v1
    depends_on:
      - database
    ports:
      - 3000:8080
      - 8888:8888
    volumes:
      - ./server:/srv/nSERVER
    links:
      - database

  database:
    container_name: 8weike-db-dev
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=8weike-db-dev-MySQL-SECRET
      - MYSQL_DATABASE=8weike_db_dev
      - MYSQL_USER=dbdevmaster
      - MYSQL_PASSWORD=dbdevmaster
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  flyway:
    container_name: 8weike-flyway-dev
    build: ./docker-flyway
    depends_on:
      - database
    image: flyway:v4.0.3
    volumes:
      - ./sql:/flyway/sql
      - ./flyway.conf:/flyway/flyway.conf
